# Minimal PyPLECS generated config
app:
  name: "PyPLECS"
  version: "0.1.0"

plecs:
  executable_paths: []

webgui:
  enabled: true
  host: "0.0.0.0"
  port: 8080

paths:
  results: "./results"
  cache: "./cache"
  logs: "./logs"
  static: "./static"
  templates: "./templates"
