app:
  name: PyPLECS
  version: 0.1.0
  debug: false
plecs:
  executable_paths:
  - D:\Plexim\PLECS 4.7 (64 bit)\PLECS.exe
  xmlrpc:
    host: localhost
    port: 1080
    timeout: 30
  priority: HIGH_PRIORITY_CLASS
  simulation:
    timeout: 300
    auto_save: true
    save_format: mat
orchestration:
  max_concurrent_simulations: 4
  queue_size: 100
  retry_attempts: 3
  retry_delay: 5
cache:
  enabled: true
  type: file
  directory: ./cache
  ttl: 3600
  storage:
    timeseries_format: parquet
    metadata_format: json
    compression: snappy
  hash:
    algorithm: sha256
    include_files: true
    include_parameters: true
    exclude_fields:
    - timestamp
    - run_id
optimizer:
  enabled: true
  algorithms:
  - scipy_minimize
  - genetic_algorithm
  - particle_swarm
  - bayesian_optimization
  defaults:
    max_iterations: 100
    tolerance: 1e-6
    population_size: 50
webgui:
  enabled: true
  host: 0.0.0.0
  port: 8080
  static_files: ./static
  templates: ./templates
  auth:
    enabled: false
    secret_key: your-secret-key-here
  monitoring:
    refresh_interval: 1000
    max_history_points: 1000
api:
  enabled: true
  host: 0.0.0.0
  port: 8081
  prefix: /api/v1
  rate_limit:
    enabled: true
    requests_per_minute: 100
  docs:
    enabled: true
    swagger_ui: true
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file:
    enabled: true
    path: ./logs/pyplecs.log
    max_size: 10MB
    backup_count: 5
    rotation: time
  console:
    enabled: true
    level: INFO
  structured:
    enabled: true
    format: json
    path: ./logs/structured.jsonl
mcp:
  enabled: true
  name: pyplecs-mcp
  version: 1.0.0
  server:
    transport: stdio
    host: localhost
    port: 3000
  tools:
  - simulation_runner
  - parameter_optimizer
  - result_analyzer
  - model_validator
database:
  enabled: false
  type: sqlite
  url: sqlite:///./pyplecs.db
  pool_size: 5
  max_overflow: 10
  echo: false
model_defaults:
  Vi: 0.0
  Vo: 0.0
  mosfet:
    Ron: 1e-6
  inductor:
    L: 1e-6
    R: 1e-3
  capacitor:
    C: 1e-6
    ESR: 1e-3
paths:
  models: ./models
  results: ./results
  cache: ./cache
  logs: ./logs
  temp: ./temp
  static: ./static
  templates: ./templates
development:
  auto_reload: true
  debug_mode: true
  profiling: false
production:
  workers: 4
  worker_connections: 1000
  keepalive: 2
