name: CI - package coherence

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  test:
    name: Test & Validate Package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upgrade pip and install build tools
        run: |
          python -m pip install --upgrade pip build setuptools wheel

      - name: Install package (editable)
        run: |
          python -m pip install -e .

      - name: Run pip check
        run: |
          python -m pip check || true

      - name: Install dev/test tools
        run: |
          python -m pip install flake8 pytest

      - name: Lint Python (flake8)
        run: |
          # Lint package and tests; keep non-blocking to avoid failing on style
          flake8 pyplecs tests || true

      - name: Run CLI tests (pytest)
        run: |
          # Run only the CLI/unit tests that are platform-independent
          pytest -q tests/test_installer.py tests/test_entrypoint.py tests/test_install_full.py

      - name: Build distribution (sanity)
        run: |
          python -m build --sdist --wheel
